### ISSUE TITLE
Could not get version for google-chrome with the any command:

### ISSUE THREAD

**Issue by TaylorWhite21** [matthewalunni/easy-apply-bot#1]
When running the "python3 easy-apply.py" command. I get the following error:

```
Could not get version for google-chrome with the any command: google-chrome --version || google-chrome-stable --version
Current google-chrome version is UNKNOWN
Get LATEST chromedriver version for UNKNOWN google-chrome
Driver [/home/penkey/.wdm/drivers/chromedriver/linux64/96.0.4664.45/chromedriver] found in cache
/home/penkey/linkedin-bot/easy-apply-bot/easy-apply.py:56: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager(chrome_type=ChromeType.GOOGLE).install())
Traceback (most recent call last):
  File "/home/penkey/linkedin-bot/easy-apply-bot/easy-apply.py", line 198, in <module>
    driver = launch_driver("https://www.linkedin.com/")
  File "/home/penkey/linkedin-bot/easy-apply-bot/easy-apply.py", line 56, in launch_driver
    driver = webdriver.Chrome(ChromeDriverManager(chrome_type=ChromeType.GOOGLE).install())
  File "/home/penkey/linkedin-bot/.venv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/penkey/linkedin-bot/.venv/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__
    self.service.start()
  File "/home/penkey/linkedin-bot/.venv/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/penkey/linkedin-bot/.venv/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /home/penkey/.wdm/drivers/chromedriver/linux64/96.0.4664.45/chromedriver unexpectedly exited. Status code was: 127
```

**Comment by matthewalunni** [comment]
Trying to reproduce. What operating system? 
Is it possible you don't have Chrome installed, or your OS doesn't know about it? 

If you're running Ubuntu, could you try this?

```pip install selenium
sudo apt-get update
sudo apt install chromium-chromedriver

**Comment by TaylorWhite21** [comment]
I am on windows using Ubuntu command line. That may be the case. I'll look into how to get it to notice it.
Tried those commands, but still doesn't work.

**Comment by TaylorWhite21** [comment]
I believe this is the answer, but I am not able to understand it at this time. I'm still a newbie :D
https://exerror.com/selenium-common-exceptions-webdriverexception-message-unknown-error-chrome-failed-to-start-crashed/
